frases=[("Hola", "Hallo!"),
    ("Buenos días", "Guten Morgen!"),
    ("Buen día", "Guten Tag"),
    ("Buenas noches", "Gute Nacht"),
    ("¿Cómo estás?", "Wie geht es dir?"),
    ("Estoy bien", "Mir geht es gut"),
    ("Me llamo ...", "Ich heiße ..."),
    ("¿De dónde eres?", "Woher kommst du?"),
    ("Vengo de Argentina", "Ich komme aus Argentinien"),
    ("Tengo hambre", "Ich habe Hunger"),
    ("Tengo sed", "Ich habe Durst"),
    ("Estoy cansado.", "Ich bin müde"),
    ("¿Dónde está el baño?", "Wo ist das Badezimmer?"),
    ("Estudio alemán", "Ich lerne Deutsch"),
    ("¿Qué te gusta hacer?", "Was machst du gern?"),
    ("Está lloviendo", "Es regnet"),
    ("Necesito ayuda", "Ich brauche Hilfe"),
    ("Hasta mañana", "Bis morgen"),
    ("Eso es interesante", "Das ist interessant"),
    ("No entiendo", "Ich verstehe nicht")
]